---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: keel-operator
  labels:
    app.kubernetes.io/name: keel
    app.kubernetes.io/component: operator

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keel-operator

subjects:
  - kind: ServiceAccount
    name: keel-operator

...
