---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: keel-operator
  labels:
    app.kubernetes.io/name: keel
    app.kubernetes.io/component: operator

rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "watch"
      - "list"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - ""
      - "extensions"
      - "apps"
      - "batch"
    resources:
      - "pods"
      - "replicasets"
      - "replicationcontrollers"
      - "statefulsets"
      - "deployments"
      - "daemonsets"
      - "jobs"
      - "cronjobs"
    verbs:
      - "get"
      - "delete"
      - "watch"
      - "list"
      - "update"
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "pods/portforward"
    verbs:
      - "get"
      - "create"
      - "update"

...
