---
apiVersion: v1
kind: Service

metadata:
  name: keel-operator
  labels:
    app.kubernetes.io/name: keel
    app.kubernetes.io/component: operator

spec:
  selector:
    app.kubernetes.io/name: keel
    app.kubernetes.io/component: operator

  ports:
    - name: http
      port: 9300
      targetPort: http

...
